apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: niksankarkee/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: niksankarkee/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: niksankarkee/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .            
    - image: niksankarkee/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .            
            
#For google cloud 
# apiVersion: skaffold/v2alpha3
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   googleCloudBuild:
#     projectId: ticketing-dev-303802
#   artifacts:
#     - image: us.gcr.io/ticketing-dev-303802/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .
#     - image: us.gcr.io/ticketing-dev-303802/client
#       context: client
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: '**/*.js'
#             dest: .
#     - image: us.gcr.io/ticketing-dev-303802/tickets
#       context: tickets
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .
#     - image: us.gcr.io/ticketing-dev-303802/orders
#       context: orders
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .